FROM mcr.microsoft.com/dotnet/sdk:9.0

WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . .

EXPOSE 8080

ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile", "--non-interactive", "--urls", "http://0.0.0.0:8080"]