include:
  - ./Services/Compute/docker-compose-dev.yml



services:
  # ================================================== #
  # ==================== Frontend ==================== #
  # ================================================== #
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    working_dir: /app
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "${FRONTEND_PORT}:3000"
    networks:
      - raion-frontend-net



  # ================================================= #
  # ==================== Gateway ==================== #
  # ================================================= #
  gateway:
    build:
      context: ./Services/Gateway
      dockerfile: Dockerfile.dev
    container_name: gateway-api-dev
    working_dir: /app
    env_file:
      - ./Services/Gateway/.env
    volumes:
      - ./Services/Gateway:/app
      - /app/bin
      - /app/obj
    ports:
      - "${GATEWAY_PORT}:8080"
    networks:
      - raion-backend-net
    command: dotnet watch run --no-launch-profile --non-interactive



  # ==================================================== #
  # ==================== Controller ==================== #
  # ==================================================== #
  controller:
    build:
      context: ./Services/Controller
      dockerfile: Dockerfile.dev
    container_name: controller-api-dev
    working_dir: /app
    env_file:
      - ./Services/Controller/.env
    volumes:
      - ./Services/Controller:/app
      - /app/bin
      - /app/obj
    ports:
      - "${CONTROLLER_PORT}:8080"
    networks:
      - raion-backend-net
    command: dotnet watch run --no-launch-profile --non-interactive



  # ================================================= #
  # ==================== Compute ==================== #
  # ================================================= #
  compute-1:
    extends:
      file: ./Services/Compute/docker-compose-dev.yml
      service: compute-template
    container_name: compute-api-dev-1
    ports:
      - "${COMPUTE_PORT_1}:8080"
    environment:
      - ConnectionStrings__Redis=redis-1:6379
    networks:
      - raion-compute-net-1
    depends_on:
      - redis-1

  redis-1:
    extends:
      file: ./Services/Compute/docker-compose-dev.yml
      service: compute-redis-template
    container_name: redis-cache-dev-1
    networks:
      - raion-compute-net-1
    volumes:
      - redis-1-data:/data



  compute-2:
    extends:
      file: ./Services/Compute/docker-compose-dev.yml
      service: compute-template
    container_name: compute-api-dev-2
    ports:
      - "${COMPUTE_PORT_2}:8080"
    networks:
      - raion-compute-net-2
    depends_on:
      - redis-2
    environment:
      - ConnectionStrings__Redis=redis-2:6379

  redis-2:
    extends:
      file: ./Services/Compute/docker-compose-dev.yml
      service: compute-redis-template
    container_name: redis-cache-dev-2
    networks:
      - raion-compute-net-2
    volumes:
      - redis-2-data:/data



  # ================================================= #
  # ==================== Identity =================== #
  # ================================================= #
  keycloak-db:
    image: postgres:16-alpine
    container_name: raion-keycloak-postgres-dev
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${KEYCLOAK_ADMIN}
      - POSTGRES_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - POSTGRES_DB=${KC_DB}
    ports:
      - "${KC_DB_URL_PORT}"
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - raion-keycloak-net
    restart: unless-stopped



  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: raion-keycloak-dev
    command: start-dev --import-realm
    ports:
      - "${KC_PORT}:8080"
    env_file:
      - .env
    environment:
      - KC_DB_URL_HOST=keycloak-db
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - raion-keycloak-net
    depends_on:
      - keycloak-db
    restart: unless-stopped



  # ======================================================= #
  # ==================== Main Database ==================== #
  # ======================================================= #
  postgres-db:
    image: postgres:16-alpine
    container_name: raion-postgres-dev
    env_file:
      - .env
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - raion-backend-net
    restart: unless-stopped



  # =================================================== #
  # ==================== Dev Tools ==================== #
  # =================================================== #
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight-web
    env_file:
      - .env
    ports:
      - "${REDIS_INSIGHT_PORT}:5540"
    networks:
      - raion-compute-net-1
      - raion-compute-net-2
    depends_on:
      - redis-1
      - redis-2



  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: raion-pgadmin-dev
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - raion-backend-net
    depends_on:
      - postgres-db
    restart: unless-stopped



  # =============================================== #
  # ==================== Setup ==================== #
  # =============================================== #
volumes:
  redis-1-data:
  redis-2-data:
  pgadmin-data:
  postgres-data:
  keycloak-data:
  keycloak-db-data:



networks:
  raion-frontend-net:
  raion-backend-net:
  raion-compute-net-1:
  raion-compute-net-2:
  raion-keycloak-net:
