include:
  - ./Services/Compute/docker-compose-dev.yml



services:
  gateway:
    build:
      context: ./Services/Gateway
      dockerfile: Dockerfile.dev
    container_name: gateway-api-dev
    working_dir: /app
    env_file:
      - ./Services/Gateway/.env
    volumes:
      - ./Services/Gateway:/app
      - /app/bin
      - /app/obj
    ports:
      - "${GATEWAY_PORT}:8080"
    command: dotnet watch run --no-launch-profile --non-interactive



  controller:
    build:
      context: ./Services/Controller
      dockerfile: Dockerfile.dev
    container_name: controller-api-dev
    working_dir: /app
    env_file:
      - ./Services/Controller/.env
    volumes:
      - ./Services/Controller:/app
      - /app/bin
      - /app/obj
    ports:
      - "${CONTROLLER_PORT}:8080"
    command: dotnet watch run --no-launch-profile --non-interactive



  compute-1:
    extends:
      file: ./Services/Compute/docker-compose-dev.yml
      service: compute-template
    container_name: compute-api-dev-1
    ports:
      - "${COMPUTE_PORT_1}:8080"

  compute-2:
    extends: 
      file: ./Services/Compute/docker-compose-dev.yml
      service: compute-template
    container_name: compute-api-dev-2
    ports:
      - "${COMPUTE_PORT_2}:8080"