services:
  # ================================================= #
  # ==================== Gateway ==================== #
  # ================================================= #
  gateway:
    build:
      context: .
      dockerfile: ./Services/Gateway/Dockerfile
    container_name: gateway-api
    restart: always
    env_file:
      - ./Services/Gateway/.env
    ports:
      - "${GATEWAY_PORT}:8080"
    networks:
      - raion-net



  # ==================================================== #
  # ==================== Controller ==================== #
  # ==================================================== #
  controller:
    build:
      context: .
      dockerfile: ./Services/Controller/Dockerfile
    container_name: controller-api
    restart: always
    env_file:
      - ./Services/Controller/.env
    networks:
      - raion-net



  # =============================================== #
  # ==================== Setup ==================== #
  # =============================================== #
networks:
  raion-net:
    driver: bridge